<?php

namespace Database\Seeders;

use App\Models\RoomMedia;
use App\Models\RoomType;
use App\Models\RoomUnit;
use Illuminate\Database\Seeder;

class RoomSeeder extends Seeder
{
    /**
     * 12 room types across 5 categories for Brickspoint Hotel, Wuse, Abuja.
     * Each type gets multiple units.
     */
    public function run(): void
    {
        $roomTypes = [
            // ── Standard (4 types) ───────────────────────────────
            [
                'name'           => 'Standard King Room',
                'slug'           => 'standard-king-room',
                'room_type'      => 'standard',
                'bed_type'       => 'king',
                'room_size'      => 28,
                'description'    => 'Comfortable king-sized room with modern amenities, perfect for solo travelers or couples. Features a work desk, plush bedding, and city views.',
                'price'          => 45000,
                'weekend_price'  => 52000,
                'holiday_price'  => 65000,
                'image'          => 'room-types/standard-king.jpg',
                'features'       => [
                    ['name' => 'King Bed', 'icon' => 'fa-bed'],
                    ['name' => 'Free WiFi', 'icon' => 'fa-wifi'],
                    ['name' => 'Air Conditioning', 'icon' => 'fa-snowflake'],
                    ['name' => 'Flat Screen TV', 'icon' => 'fa-tv'],
                    ['name' => 'Mini Fridge', 'icon' => 'fa-cube'],
                    ['name' => 'En-suite Bathroom', 'icon' => 'fa-bath'],
                    ['name' => 'Work Desk', 'icon' => 'fa-desktop'],
                    ['name' => 'Coffee/Tea Maker', 'icon' => 'fa-mug-hot'],
                ],
                'base_guests'    => 2,
                'max_guests'     => 2,
                'extra_guest_fee' => 15000,
                'min_stay'       => 1,
                'is_active'      => true,
                'is_featured'    => true,
                'sort_order'     => 1,
                'units'          => [
                    ['unit_number' => '101', 'floor' => 1, 'status' => 'available'],
                    ['unit_number' => '102', 'floor' => 1, 'status' => 'available'],
                ],
            ],
            [
                'name'           => 'Standard Twin Room',
                'slug'           => 'standard-twin-room',
                'room_type'      => 'standard',
                'bed_type'       => 'twin',
                'room_size'      => 28,
                'description'    => 'Twin room with two single beds, ideal for friends or colleagues traveling together. Same modern comforts as our king room with flexible sleeping arrangements.',
                'price'          => 45000,
                'weekend_price'  => 52000,
                'holiday_price'  => 65000,
                'image'          => 'room-types/standard-twin.jpg',
                'features'       => [
                    ['name' => 'Two Single Beds', 'icon' => 'fa-bed'],
                    ['name' => 'Free WiFi', 'icon' => 'fa-wifi'],
                    ['name' => 'Air Conditioning', 'icon' => 'fa-snowflake'],
                    ['name' => 'Flat Screen TV', 'icon' => 'fa-tv'],
                    ['name' => 'Mini Fridge', 'icon' => 'fa-cube'],
                    ['name' => 'En-suite Bathroom', 'icon' => 'fa-bath'],
                    ['name' => 'Work Desk', 'icon' => 'fa-desktop'],
                    ['name' => 'Coffee/Tea Maker', 'icon' => 'fa-mug-hot'],
                ],
                'base_guests'    => 2,
                'max_guests'     => 2,
                'extra_guest_fee' => 15000,
                'min_stay'       => 1,
                'is_active'      => true,
                'is_featured'    => false,
                'sort_order'     => 2,
                'units'          => [
                    ['unit_number' => '103', 'floor' => 1, 'status' => 'available'],
                    ['unit_number' => '104', 'floor' => 1, 'status' => 'available'],
                ],
            ],
            [
                'name'           => 'Standard Queen Room',
                'slug'           => 'standard-queen-room',
                'room_type'      => 'standard',
                'bed_type'       => 'queen',
                'room_size'      => 26,
                'description'    => 'Cozy queen room offering great value with all essential amenities. Perfect for short business trips or weekend getaways.',
                'price'          => 40000,
                'weekend_price'  => 47000,
                'holiday_price'  => 58000,
                'image'          => 'room-types/standard-queen.jpg',
                'features'       => [
                    ['name' => 'Queen Bed', 'icon' => 'fa-bed'],
                    ['name' => 'Free WiFi', 'icon' => 'fa-wifi'],
                    ['name' => 'Air Conditioning', 'icon' => 'fa-snowflake'],
                    ['name' => 'Flat Screen TV', 'icon' => 'fa-tv'],
                    ['name' => 'Mini Fridge', 'icon' => 'fa-cube'],
                    ['name' => 'En-suite Bathroom', 'icon' => 'fa-bath'],
                    ['name' => 'Coffee/Tea Maker', 'icon' => 'fa-mug-hot'],
                ],
                'base_guests'    => 2,
                'max_guests'     => 3,
                'extra_guest_fee' => 12000,
                'min_stay'       => 1,
                'is_active'      => true,
                'is_featured'    => false,
                'sort_order'     => 3,
                'units'          => [
                    ['unit_number' => '105', 'floor' => 1, 'status' => 'available'],
                    ['unit_number' => '106', 'floor' => 1, 'status' => 'available'],
                ],
            ],
            [
                'name'           => 'Standard Double Room',
                'slug'           => 'standard-double-room',
                'room_type'      => 'standard',
                'bed_type'       => 'double',
                'room_size'      => 26,
                'description'    => 'Budget-friendly double room with a double bed, offering comfort and convenience for the practical traveler.',
                'price'          => 38000,
                'weekend_price'  => 44000,
                'holiday_price'  => 55000,
                'image'          => 'room-types/standard-double.jpg',
                'features'       => [
                    ['name' => 'Double Bed', 'icon' => 'fa-bed'],
                    ['name' => 'Free WiFi', 'icon' => 'fa-wifi'],
                    ['name' => 'Air Conditioning', 'icon' => 'fa-snowflake'],
                    ['name' => 'Flat Screen TV', 'icon' => 'fa-tv'],
                    ['name' => 'Mini Fridge', 'icon' => 'fa-cube'],
                    ['name' => 'En-suite Bathroom', 'icon' => 'fa-bath'],
                    ['name' => 'Coffee/Tea Maker', 'icon' => 'fa-mug-hot'],
                ],
                'base_guests'    => 2,
                'max_guests'     => 2,
                'extra_guest_fee' => 12000,
                'min_stay'       => 1,
                'is_active'      => true,
                'is_featured'    => false,
                'sort_order'     => 4,
                'units'          => [
                    ['unit_number' => '107', 'floor' => 1, 'status' => 'available'],
                    ['unit_number' => '108', 'floor' => 1, 'status' => 'available'],
                ],
            ],

            // ── Deluxe (3 types) ───────────────────────────────
            [
                'name'           => 'Deluxe King Suite',
                'slug'           => 'deluxe-king-suite',
                'room_type'      => 'deluxe',
                'bed_type'       => 'king',
                'room_size'      => 42,
                'description'    => 'Spacious deluxe room with separate sitting area, king bed, and premium amenities. Includes a sofa bed for additional guest flexibility.',
                'price'          => 75000,
                'weekend_price'  => 85000,
                'holiday_price'  => 105000,
                'image'          => 'room-types/deluxe-king.jpg',
                'features'       => [
                    ['name' => 'King Bed', 'icon' => 'fa-bed'],
                    ['name' => 'Sofa Bed', 'icon' => 'fa-couch'],
                    ['name' => 'Free WiFi', 'icon' => 'fa-wifi'],
                    ['name' => 'Air Conditioning', 'icon' => 'fa-snowflake'],
                    ['name' => '55" Smart TV', 'icon' => 'fa-tv'],
                    ['name' => 'Mini Bar', 'icon' => 'fa-wine-glass'],
                    ['name' => 'En-suite Bathroom with Tub', 'icon' => 'fa-bath'],
                    ['name' => 'Work Desk', 'icon' => 'fa-desktop'],
                    ['name' => 'Coffee/Tea Maker', 'icon' => 'fa-mug-hot'],
                    ['name' => 'Bathrobe & Slippers', 'icon' => 'fa-user-tie'],
                ],
                'base_guests'    => 2,
                'max_guests'     => 3,
                'extra_guest_fee' => 20000,
                'min_stay'       => 1,
                'is_active'      => true,
                'is_featured'    => true,
                'sort_order'     => 10,
                'units'          => [
                    ['unit_number' => '201', 'floor' => 2, 'status' => 'available'],
                    ['unit_number' => '202', 'floor' => 2, 'status' => 'available'],
                ],
            ],
            [
                'name'           => 'Deluxe Twin Room',
                'slug'           => 'deluxe-twin-room',
                'room_type'      => 'deluxe',
                'bed_type'       => 'twin',
                'room_size'      => 40,
                'description'    => 'Deluxe twin room with two queen beds and a sitting area. Perfect for families or small groups wanting extra space and comfort.',
                'price'          => 78000,
                'weekend_price'  => 88000,
                'holiday_price'  => 108000,
                'image'          => 'room-types/deluxe-twin.jpg',
                'features'       => [
                    ['name' => 'Two Queen Beds', 'icon' => 'fa-bed'],
                    ['name' => 'Sitting Area', 'icon' => 'fa-couch'],
                    ['name' => 'Free WiFi', 'icon' => 'fa-wifi'],
                    ['name' => 'Air Conditioning', 'icon' => 'fa-snowflake'],
                    ['name' => '55" Smart TV', 'icon' => 'fa-tv'],
                    ['name' => 'Mini Bar', 'icon' => 'fa-wine-glass'],
                    ['name' => 'En-suite Bathroom with Tub', 'icon' => 'fa-bath'],
                    ['name' => 'Work Desk', 'icon' => 'fa-desktop'],
                    ['name' => 'Coffee/Tea Maker', 'icon' => 'fa-mug-hot'],
                    ['name' => 'Bathrobe & Slippers', 'icon' => 'fa-user-tie'],
                ],
                'base_guests'    => 4,
                'max_guests'     => 4,
                'extra_guest_fee' => 20000,
                'min_stay'       => 1,
                'is_active'      => true,
                'is_featured'    => false,
                'sort_order'     => 11,
                'units'          => [
                    ['unit_number' => '203', 'floor' => 2, 'status' => 'available'],
                    ['unit_number' => '204', 'floor' => 2, 'status' => 'available'],
                ],
            ],
            [
                'name'           => 'Deluxe Executive King',
                'slug'           => 'deluxe-executive-king',
                'room_type'      => 'deluxe',
                'bed_type'       => 'king',
                'room_size'      => 45,
                'description'    => 'Executive deluxe room with city skyline views, premium work station, and exclusive access to executive lounge services.',
                'price'          => 85000,
                'weekend_price'  => 95000,
                'holiday_price'  => 115000,
                'image'          => 'room-types/deluxe-executive.jpg',
                'features'       => [
                    ['name' => 'King Bed', 'icon' => 'fa-bed'],
                    ['name' => 'Sofa Bed', 'icon' => 'fa-couch'],
                    ['name' => 'Free WiFi', 'icon' => 'fa-wifi'],
                    ['name' => 'Air Conditioning', 'icon' => 'fa-snowflake'],
                    ['name' => '65" Smart TV', 'icon' => 'fa-tv'],
                    ['name' => 'Mini Bar', 'icon' => 'fa-wine-glass'],
                    ['name' => 'En-suite Bathroom with Jacuzzi Tub', 'icon' => 'fa-hot-tub'],
                    ['name' => 'Premium Work Station', 'icon' => 'fa-laptop'],
                    ['name' => 'Nespresso Machine', 'icon' => 'fa-coffee'],
                    ['name' => 'Bathrobe & Slippers', 'icon' => 'fa-user-tie'],
                    ['name' => 'Executive Lounge Access', 'icon' => 'fa-door-open'],
                ],
                'base_guests'    => 2,
                'max_guests'     => 3,
                'extra_guest_fee' => 25000,
                'min_stay'       => 1,
                'is_active'      => true,
                'is_featured'    => true,
                'sort_order'     => 12,
                'units'          => [
                    ['unit_number' => '205', 'floor' => 2, 'status' => 'available'],
                    ['unit_number' => '206', 'floor' => 2, 'status' => 'available'],
                ],
            ],

            // ── Suite (2 types) ────────────────────────────────
            [
                'name'           => 'Junior Suite',
                'slug'           => 'junior-suite',
                'room_type'      => 'suite',
                'bed_type'       => 'king',
                'room_size'      => 55,
                'description'    => 'Elegant junior suite with separate living room, king bedroom, and dining area. Ideal for extended stays or guests wanting extra space.',
                'price'          => 120000,
                'weekend_price'  => 135000,
                'holiday_price'  => 160000,
                'image'          => 'room-types/junior-suite.jpg',
                'features'       => [
                    ['name' => 'King Bed', 'icon' => 'fa-bed'],
                    ['name' => 'Separate Living Room', 'icon' => 'fa-couch'],
                    ['name' => 'Dining Area', 'icon' => 'fa-utensils'],
                    ['name' => 'Free WiFi', 'icon' => 'fa-wifi'],
                    ['name' => 'Dual Zone AC', 'icon' => 'fa-snowflake'],
                    ['name' => '65" Smart TV (Bedroom)', 'icon' => 'fa-tv'],
                    ['name' => '55" Smart TV (Living)', 'icon' => 'fa-tv'],
                    ['name' => 'Full Mini Bar', 'icon' => 'fa-wine-bottle'],
                    ['name' => 'En-suite Bathroom with Jacuzzi', 'icon' => 'fa-hot-tub'],
                    ['name' => 'Work Desk', 'icon' => 'fa-desktop'],
                    ['name' => 'Nespresso Machine', 'icon' => 'fa-coffee'],
                    ['name' => 'Bathrobe & Slippers', 'icon' => 'fa-user-tie'],
                ],
                'base_guests'    => 2,
                'max_guests'     => 4,
                'extra_guest_fee' => 30000,
                'min_stay'       => 2,
                'is_active'      => true,
                'is_featured'    => true,
                'sort_order'     => 20,
                'units'          => [
                    ['unit_number' => '301', 'floor' => 3, 'status' => 'available'],
                    ['unit_number' => '302', 'floor' => 3, 'status' => 'available'],
                ],
            ],
            [
                'name'           => 'Family Suite',
                'slug'           => 'family-suite',
                'room_type'      => 'suite',
                'bed_type'       => 'twin',
                'room_size'      => 65,
                'description'    => 'Spacious family suite with master bedroom (king), second bedroom (twin), shared living/dining area. Perfect for families with children.',
                'price'          => 145000,
                'weekend_price'  => 160000,
                'holiday_price'  => 190000,
                'image'          => 'room-types/family-suite.jpg',
                'features'       => [
                    ['name' => 'King Bed (Master)', 'icon' => 'fa-bed'],
                    ['name' => 'Twin Beds (Second Room)', 'icon' => 'fa-bed'],
                    ['name' => 'Separate Living Room', 'icon' => 'fa-couch'],
                    ['name' => 'Dining Area', 'icon' => 'fa-utensils'],
                    ['name' => 'Free WiFi', 'icon' => 'fa-wifi'],
                    ['name' => 'Dual Zone AC', 'icon' => 'fa-snowflake'],
                    ['name' => 'Smart TVs in Both Rooms', 'icon' => 'fa-tv'],
                    ['name' => 'Full Mini Bar', 'icon' => 'fa-wine-bottle'],
                    ['name' => 'Two Bathrooms (One with Tub)', 'icon' => 'fa-bath'],
                    ['name' => 'Work Desk', 'icon' => 'fa-desktop'],
                    ['name' => 'Nespresso Machine', 'icon' => 'fa-coffee'],
                    ['name' => 'Bathrobe & Slippers', 'icon' => 'fa-user-tie'],
                    ['name' => "Kids' Amenities Available", 'icon' => 'fa-child'],
                ],
                'base_guests'    => 4,
                'max_guests'     => 6,
                'extra_guest_fee' => 30000,
                'min_stay'       => 2,
                'is_active'      => true,
                'is_featured'    => false,
                'sort_order'     => 21,
                'units'          => [
                    ['unit_number' => '303', 'floor' => 3, 'status' => 'available'],
                    ['unit_number' => '304', 'floor' => 3, 'status' => 'available'],
                ],
            ],

            // ── Executive (2 types) ────────────────────────────
            [
                'name'           => 'Executive Suite',
                'slug'           => 'executive-suite',
                'room_type'      => 'executive',
                'bed_type'       => 'king',
                'room_size'      => 75,
                'description'    => 'Luxurious executive suite with panoramic city views, separate living/dining rooms, kitchenette, and butler service. Designed for discerning business and leisure travelers.',
                'price'          => 195000,
                'weekend_price'  => 215000,
                'holiday_price'  => 250000,
                'image'          => 'room-types/executive-suite.jpg',
                'features'       => [
                    ['name' => 'King Bed', 'icon' => 'fa-bed'],
                    ['name' => 'Separate Living Room', 'icon' => 'fa-couch'],
                    ['name' => 'Dining Room', 'icon' => 'fa-utensils'],
                    ['name' => 'Kitchenette', 'icon' => 'fa-kitchen-set'],
                    ['name' => 'Free WiFi', 'icon' => 'fa-wifi'],
                    ['name' => 'Dual Zone AC', 'icon' => 'fa-snowflake'],
                    ['name' => '75" Smart TV (Living)', 'icon' => 'fa-tv'],
                    ['name' => '55" Smart TV (Bedroom)', 'icon' => 'fa-tv'],
                    ['name' => 'Premium Mini Bar', 'icon' => 'fa-wine-bottle'],
                    ['name' => 'En-suite Bathroom with Jacuzzi & Steam', 'icon' => 'fa-hot-tub'],
                    ['name' => 'Executive Work Station', 'icon' => 'fa-laptop'],
                    ['name' => 'Nespresso Machine', 'icon' => 'fa-coffee'],
                    ['name' => 'Butler Service', 'icon' => 'fa-concierge-bell'],
                    ['name' => 'Executive Lounge Access', 'icon' => 'fa-door-open'],
                    ['name' => 'Bathrobe & Slippers', 'icon' => 'fa-user-tie'],
                ],
                'base_guests'    => 2,
                'max_guests'     => 4,
                'extra_guest_fee' => 35000,
                'min_stay'       => 2,
                'is_active'      => true,
                'is_featured'    => true,
                'sort_order'     => 30,
                'units'          => [
                    ['unit_number' => '401', 'floor' => 4, 'status' => 'available'],
                    ['unit_number' => '402', 'floor' => 4, 'status' => 'available'],
                ],
            ],
            [
                'name'           => 'Executive Corner Suite',
                'slug'           => 'executive-corner-suite',
                'room_type'      => 'executive',
                'bed_type'       => 'king',
                'room_size'      => 85,
                'description'    => 'Premium corner suite with floor-to-ceiling windows, 270-degree city views, private terrace, and dedicated butler. The ultimate luxury experience.',
                'price'          => 230000,
                'weekend_price'  => 255000,
                'holiday_price'  => 295000,
                'image'          => 'room-types/executive-corner.jpg',
                'features'       => [
                    ['name' => 'King Bed', 'icon' => 'fa-bed'],
                    ['name' => 'Separate Living Room', 'icon' => 'fa-couch'],
                    ['name' => 'Dining Room', 'icon' => 'fa-utensils'],
                    ['name' => 'Private Terrace', 'icon' => 'fa-tree-city'],
                    ['name' => 'Kitchenette', 'icon' => 'fa-kitchen-set'],
                    ['name' => 'Free WiFi', 'icon' => 'fa-wifi'],
                    ['name' => 'Dual Zone AC', 'icon' => 'fa-snowflake'],
                    ['name' => '75" Smart TV (Living)', 'icon' => 'fa-tv'],
                    ['name' => '65" Smart TV (Bedroom)', 'icon' => 'fa-tv'],
                    ['name' => 'Premium Mini Bar', 'icon' => 'fa-wine-bottle'],
                    ['name' => 'En-suite Bathroom with Jacuzzi, Steam & Sauna', 'icon' => 'fa-hot-tub'],
                    ['name' => 'Executive Work Station', 'icon' => 'fa-laptop'],
                    ['name' => 'Nespresso Machine', 'icon' => 'fa-coffee'],
                    ['name' => '24/7 Butler Service', 'icon' => 'fa-concierge-bell'],
                    ['name' => 'Executive Lounge Access', 'icon' => 'fa-door-open'],
                    ['name' => 'Bathrobe & Slippers', 'icon' => 'fa-user-tie'],
                    ['name' => 'Complimentary Airport Transfer', 'icon' => 'fa-plane'],
                ],
                'base_guests'    => 2,
                'max_guests'     => 4,
                'extra_guest_fee' => 40000,
                'min_stay'       => 2,
                'is_active'      => true,
                'is_featured'    => true,
                'sort_order'     => 31,
                'units'          => [
                    ['unit_number' => '403', 'floor' => 4, 'status' => 'available'],
                    ['unit_number' => '404', 'floor' => 4, 'status' => 'available'],
                ],
            ],

            // ── Presidential (1 type) ──────────────────────────
            [
                'name'           => 'Presidential Suite',
                'slug'           => 'presidential-suite',
                'room_type'      => 'presidential',
                'bed_type'       => 'king',
                'room_size'      => 120,
                'description'    => 'The crown jewel of Brickspoint Hotel. Two master bedrooms, grand living/dining, private study, kitchen, terrace with city views, and 24/7 dedicated butler. Reserved for VIPs and special occasions.',
                'price'          => 450000,
                'weekend_price'  => 495000,
                'holiday_price'  => 580000,
                'image'          => 'room-types/presidential-suite.jpg',
                'features'       => [
                    ['name' => 'Two King Master Bedrooms', 'icon' => 'fa-bed'],
                    ['name' => 'Grand Living Room', 'icon' => 'fa-couch'],
                    ['name' => 'Formal Dining Room', 'icon' => 'fa-utensils'],
                    ['name' => 'Private Study', 'icon' => 'fa-book'],
                    ['name' => 'Full Kitchen', 'icon' => 'fa-kitchen-set'],
                    ['name' => 'Private Terrace', 'icon' => 'fa-tree-city'],
                    ['name' => 'Free WiFi', 'icon' => 'fa-wifi'],
                    ['name' => 'Multi-Zone Climate Control', 'icon' => 'fa-snowflake'],
                    ['name' => '85" Smart TV (Living)', 'icon' => 'fa-tv'],
                    ['name' => '65" Smart TVs (Bedrooms)', 'icon' => 'fa-tv'],
                    ['name' => 'Stocked Premium Bar', 'icon' => 'fa-wine-bottle'],
                    ['name' => 'Master Bath with Jacuzzi, Steam, Sauna', 'icon' => 'fa-hot-tub'],
                    ['name' => 'Second Full Bathroom', 'icon' => 'fa-bath'],
                    ['name' => 'Executive Work Station', 'icon' => 'fa-laptop'],
                    ['name' => 'Nespresso + Espresso Machine', 'icon' => 'fa-coffee'],
                    ['name' => '24/7 Dedicated Butler', 'icon' => 'fa-concierge-bell'],
                    ['name' => 'Executive Lounge Access', 'icon' => 'fa-door-open'],
                    ['name' => 'Luxury Bathrobes & Slippers', 'icon' => 'fa-user-tie'],
                    ['name' => 'Complimentary Airport Transfer', 'icon' => 'fa-plane'],
                    ['name' => 'Priority Check-in/Check-out', 'icon' => 'fa-fast-forward'],
                ],
                'base_guests'    => 4,
                'max_guests'     => 6,
                'extra_guest_fee' => 50000,
                'min_stay'       => 3,
                'is_active'      => true,
                'is_featured'    => true,
                'sort_order'     => 40,
                'units'          => [
                    ['unit_number' => '501', 'floor' => 5, 'status' => 'available'],
                ],
            ],
        ];

        foreach ($roomTypes as $typeData) {
            $units = $typeData['units'];
            unset($typeData['units']);

            $roomType = RoomType::updateOrCreate(
                ['slug' => $typeData['slug']],
                $typeData,
            );

            // Create units for this type
            foreach ($units as $unitData) {
                RoomUnit::updateOrCreate(
                    ['room_type_id' => $roomType->id, 'unit_number' => $unitData['unit_number']],
                    array_merge($unitData, ['room_type_id' => $roomType->id]),
                );
            }

            // Add sample media for each room type
            $mediaFiles = [
                'main' => $typeData['image'],
                'living' => str_replace('.jpg', '-living.jpg', $typeData['image']),
                'bathroom' => str_replace('.jpg', '-bathroom.jpg', $typeData['image']),
                'view' => str_replace('.jpg', '-view.jpg', $typeData['image']),
            ];

            foreach ($mediaFiles as $key => $path) {
                RoomMedia::updateOrCreate(
                    ['room_type_id' => $roomType->id, 'file_path' => $path],
                    [
                        'type'       => 'image',
                        'sort_order' => $key === 'main' ? 1 : ($key === 'living' ? 2 : ($key === 'bathroom' ? 3 : 4)),
                        'caption'    => ucfirst($key) . ' view',
                        'alt_text'   => $typeData['name'] . ' - ' . ucfirst($key),
                    ],
                );
            }
        }
    }
}