<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PageController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\RoomController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\ContactController;
use Illuminate\Support\Facades\Auth;

// Public Routes
Route::get('/', [PageController::class, 'home'])->name('home');
Route::get('/rooms', [PageController::class, 'rooms'])->name('rooms');
Route::get('/rooms/{room}', [PageController::class, 'showRoom'])->name('rooms.show'); // New Route
Route::get('/gallery', [PageController::class, 'gallery'])->name('gallery');
Route::post('/contact', [PageController::class, 'storeContact'])->name('contact.store');

// Admin Routes
Route::prefix('admin')->name('admin.')->middleware('auth')->group(function () {
    Route::get('/dashboard', [AdminController::class, 'dashboard'])->name('dashboard');

    // Room Media Routes
    Route::post('/rooms/{room}/media', [RoomController::class, 'storeMedia'])->name('rooms.media.store');
    Route::delete('/rooms/media/{media}', [RoomController::class, 'destroyMedia'])->name('rooms.media.destroy');

    Route::resource('rooms', RoomController::class);
    Route::resource('settings', SettingController::class);
    Route::get('gallery', [GalleryController::class, 'index'])->name('gallery.index');
    Route::post('gallery', [GalleryController::class, 'store'])->name('gallery.store');
    Route::delete('gallery/{gallery}', [GalleryController::class, 'destroy'])->name('gallery.destroy');
    Route::get('contacts', [ContactController::class, 'index'])->name('contacts.index');
    Route::get('contacts/{contact}', [ContactController::class, 'show'])->name('contacts.show');
    Route::post('contacts/{contact}/toggle-read', [ContactController::class, 'toggleRead'])->name('contacts.toggleRead');
    Route::delete('contacts/{contact}', [ContactController::class, 'destroy'])->name('contacts.destroy');
});

// Auth routes generated by Laravel UI
Auth::routes();
